services:
    consumer:
        container_name: tevs_websocket_demo
        restart: unless-stopped
        build:
            context: server
            dockerfile: Dockerfile
        image: tevs_websocket_demo:latest
        ports:
          - "4001:4001"

networks:
  default:
      name: webapp_network
      external: true